# Site settings
title: Yes I Found me!
email: maheshforindia@github.com
description: > # A website to find yourself in this planet.
baseurl: "" # 
url: "http://maheshforindia.github.io/yesifoundme" # the base hostname & protocol for your site
github_username:  maheshforindia

# Build settings
markdown: kramdown